// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Metrics describes current resource usage for the running PortWeave process.
 */
export interface Metrics {
    "CPUPercent": number;
    "MemoryBytes": number;
}
