// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as port$0 from "../port/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../../../time/models.js";

/**
 * AddressMode selects how UI addresses are converted to protocol offsets.
 */
export enum AddressMode {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    AddressModeZeroBased = "zero-based",
    AddressModePLC = "plc",
};

/**
 * BoolPoint is one address/value entry in a boolean Modbus table.
 */
export interface BoolPoint {
    "Address": number;
    "Value": boolean;
}

/**
 * DataModelSnapshot is the serializable representation of a slave data model.
 */
export interface DataModelSnapshot {
    "Coils": BoolPoint[] | null;
    "DiscreteInputs": BoolPoint[] | null;
    "InputRegisters": RegisterPoint[] | null;
    "HoldingRegisters": RegisterPoint[] | null;
}

/**
 * DataType selects how register words are interpreted.
 */
export enum DataType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    DataTypeNone = "none",
    DataTypeInt16 = "int16",
    DataTypeUint16 = "uint16",
    DataTypeInt32 = "int32",
    DataTypeUint32 = "uint32",
    DataTypeInt64 = "int64",
    DataTypeUint64 = "uint64",
    DataTypeFloat = "float",
    DataTypeDouble = "double",
    DataTypeUnix = "unix",
    DataTypeDateTime = "datetime",
    DataTypeUTF8 = "utf8",
};

/**
 * DecodedRegisterValue is one interpreted register value.
 */
export interface DecodedRegisterValue {
    "DataType": DataType;
    "Raw": number[] | null;
    "Display": string;
    "Numeric": number;
}

/**
 * FrameMode selects the Modbus serial framing format.
 */
export enum FrameMode {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    FrameModeRTU = "rtu",
    FrameModeASCII = "ascii",
};

/**
 * FunctionCode is a Modbus function byte.
 */
export enum FunctionCode {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    FunctionReadCoils = 1,
    FunctionReadDiscreteInputs = 2,
    FunctionReadHoldingRegisters = 3,
    FunctionReadInputRegisters = 4,
    FunctionWriteSingleCoil = 5,
    FunctionWriteSingleRegister = 6,
    FunctionWriteMultipleCoils = 15,
    FunctionWriteMultipleRegisters = 16,
};

/**
 * LinearInterpolation maps a decoded numeric value from x1-x2 into y1-y2.
 */
export interface LinearInterpolation {
    "X1": number;
    "X2": number;
    "Y1": number;
    "Y2": number;
}

/**
 * MappedRegisterValue is one decoded configured register.
 */
export interface MappedRegisterValue {
    "Address": number;
    "Mapping": RegisterMapping;
    "Value": DecodedRegisterValue;
    "Error": string;
}

/**
 * MasterRequest describes one Modbus master transaction.
 */
export interface MasterRequest {
    "SessionID": string;
    "UnitID": number;
    "Function": FunctionCode;
    "AddressMode": AddressMode;
    "Address": number;
    "Quantity": number;
    "Value": number;
    "CoilValues": boolean[] | null;
    "RegisterValues": number[] | null;
    "TimeoutMs": number;
    "Retries": number;
}

/**
 * OpenSessionRequest opens a dedicated Modbus serial session.
 */
export interface OpenSessionRequest {
    "ID": string;
    "Name": string;
    "Mode": FrameMode;
    "Role": SessionRole;
    "Config": port$0.SerialConfig;
    "Endpoint": string;
    "TimeoutMs": number;
    "Retries": number;
}

/**
 * PDU is the function byte plus function-specific data.
 */
export interface PDU {
    "Function": FunctionCode;
    "Data": string | null;
}

/**
 * ParsedResponse is a decoded master-side response.
 */
export interface ParsedResponse {
    "Function": FunctionCode;
    "Exception": boolean;
    "ExceptionCode": number;
    "Address": number;
    "Quantity": number;
    "Value": number;
    "Values": number[] | null;
    "Bits": boolean[] | null;
    "Raw": string | null;
}

/**
 * RegisterMapping describes a configured register value in a read map.
 */
export interface RegisterMapping {
    "Address": number;
    "DataType": DataType;
    "WordOrder": WordOrder;
    "Length": number;
    "ScalingFactor": number;
    "Comment": string;
    "Interpolate": LinearInterpolation | null;
    "GroupEnd": boolean;
}

/**
 * RegisterPoint is one address/value entry in a register Modbus table.
 */
export interface RegisterPoint {
    "Address": number;
    "Value": number;
}

/**
 * RegisterReadRequest reads one register/coil block and optionally decodes mappings.
 */
export interface RegisterReadRequest {
    "SessionID": string;
    "UnitID": number;
    "Function": FunctionCode;
    "AddressMode": AddressMode;
    "Address": number;
    "Quantity": number;
    "Mappings": RegisterMapping[] | null;
    "TimeoutMs": number;
    "Retries": number;
}

/**
 * RegisterReadResult contains raw and mapped read data.
 */
export interface RegisterReadResult {
    "Transaction": Transaction | null;
    "RawRegisters": number[] | null;
    "Bits": boolean[] | null;
    "Values": MappedRegisterValue[] | null;
}

/**
 * RegisterScanRange is one scanned read chunk.
 */
export interface RegisterScanRange {
    "Address": number;
    "Quantity": number;
    "Error": string;
}

/**
 * RegisterScanRequest scans a register range in chunks.
 */
export interface RegisterScanRequest {
    "SessionID": string;
    "UnitID": number;
    "Function": FunctionCode;
    "AddressMode": AddressMode;
    "StartAddress": number;
    "EndAddress": number;
    "ChunkSize": number;
    "TimeoutMs": number;
    "Retries": number;
}

/**
 * RegisterScanResult reports non-zero register values and range errors.
 */
export interface RegisterScanResult {
    "SessionID": string;
    "UnitID": number;
    "Values": RegisterScanValue[] | null;
    "Ranges": RegisterScanRange[] | null;
}

/**
 * RegisterScanValue is a non-zero register discovered during a scan.
 */
export interface RegisterScanValue {
    "Address": number;
    "Value": number;
}

/**
 * SessionInfo is a frontend-safe snapshot of a Modbus serial session.
 */
export interface SessionInfo {
    "ID": string;
    "Name": string;
    "Mode": FrameMode;
    "Role": SessionRole;
    "Config": port$0.SerialConfig;
    "Status": string;
    "RxBytes": number;
    "TxBytes": number;
    "SlaveRunning": boolean;
    "UnitID": number;
    "UnitIDs": number[] | null;
    "StartedAt": time$0.Time;
    "StoppedAt": time$0.Time;
    "LastError": string;
}

/**
 * SessionRole fixes whether a Modbus session is used as a master or slave.
 */
export enum SessionRole {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    SessionRoleMaster = "master",
    SessionRoleSlave = "slave",
};

/**
 * SlaveUnitInfo is a frontend-safe snapshot of a simulated unit.
 */
export interface SlaveUnitInfo {
    "UnitID": number;
    "DataModel": DataModelSnapshot;
}

/**
 * SlaveUnitSnapshot is one independent simulated Modbus slave address.
 */
export interface SlaveUnitSnapshot {
    "UnitID": number;
    "DataModel": DataModelSnapshot;
}

/**
 * StartSlaveRequest starts slave simulation for one open session.
 */
export interface StartSlaveRequest {
    "SessionID": string;
    "UnitID": number;
    "DataModel": DataModelSnapshot;
    "Units": SlaveUnitSnapshot[] | null;
}

/**
 * Transaction captures one master request/response.
 */
export interface Transaction {
    "ID": string;
    "SessionID": string;
    "StartedAt": time$0.Time;
    "CompletedAt": time$0.Time;
    "UnitID": number;
    "Mode": FrameMode;
    "RequestPDU": PDU;
    "ResponsePDU": PDU;
    "RequestFrameHex": string;
    "ResponseFrameHex": string;
    "BytesWritten": number;
    "Response": ParsedResponse;
    "Error": string;
}

/**
 * UnitScanEntry is one Unit ID probe result.
 */
export interface UnitScanEntry {
    "UnitID": number;
    "Active": boolean;
    "Error": string;
}

/**
 * UnitScanRequest probes a set of Unit IDs with a small read request.
 */
export interface UnitScanRequest {
    "SessionID": string;
    "UnitIDs": number[] | null;
    "Function": FunctionCode;
    "AddressMode": AddressMode;
    "Address": number;
    "Quantity": number;
    "TimeoutMs": number;
    "Retries": number;
}

/**
 * UnitScanResult reports which Unit IDs responded.
 */
export interface UnitScanResult {
    "SessionID": string;
    "ActiveUnitIDs": number[] | null;
    "Results": UnitScanEntry[] | null;
}

/**
 * WordOrder controls the order of 16-bit registers for 32/64-bit values.
 */
export enum WordOrder {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    WordOrderBig = "big",
    WordOrderLittle = "little",
};
