// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as port$0 from "../port/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../../../time/models.js";

/**
 * Frame is one captured data or status record.
 */
export interface Frame {
    "Seq": number;
    "Timestamp": time$0.Time;
    "Direction": string;
    "Port": string;
    "Length": number;
    "Data": string | null;
    "DisplayText": string;
    "DisplayHex": string;
    "DisplayDec": string;
    "DisplayOct": string;
    "DisplayBin": string;
    "Encoding": string;
}

/**
 * FramePage is a filtered frame page.
 */
export interface FramePage {
    "Frames": Frame[] | null;
    "Total": number;
    "NextOffset": number;
}

/**
 * QueryRequest asks for a filtered page of frames.
 */
export interface QueryRequest {
    "MonitorID": string;
    "Offset": number;
    "Limit": number;
    "Direction": string;
    "Search": string;
}

/**
 * SessionInfo is a frontend-safe snapshot of a monitor session.
 */
export interface SessionInfo {
    "ID": string;
    "Name": string;
    "Provider": string;
    "PortA": string;
    "PortB": string;
    "ExternalPort": string;
    "AutoVirtualPortID": string;
    "Config": port$0.SerialConfig;
    "Encoding": string;
    "Status": string;
    "RxBytes": number;
    "TxBytes": number;
    "FrameCount": number;
    "StartedAt": time$0.Time;
    "StoppedAt": time$0.Time;
    "Error": string;
}

/**
 * StartRequest starts a serial monitor session.
 */
export interface StartRequest {
    "ID": string;
    "Name": string;
    "Provider": string;
    "PortA": string;
    "PortB": string;
    "EndpointA": string;
    "EndpointB": string;
    "ExternalPort": string;
    "AutoVirtualPortID": string;
    "Config": port$0.SerialConfig;
    "Encoding": string;
}
