// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as port$0 from "../port/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../../../time/models.js";

/**
 * AutoSaveOptions controls automatic frame persistence.
 */
export interface AutoSaveOptions {
    "Enabled": boolean;
    "Path": string;
    "Directory": string;
    "BaseName": string;
    "Format": string;
    "SplitMode": string;
    "SplitSizeKB": number;
    "SplitIntervalSeconds": number;
    "Encoding": string;
}

/**
 * AutoSaveRequest updates a session's automatic save settings.
 */
export interface AutoSaveRequest {
    "MonitorID": string;
    "Options": AutoSaveOptions;
}

/**
 * ExportRequest exports monitor frames.
 */
export interface ExportRequest {
    "MonitorID": string;
    "Format": string;
    "Path": string;
    "Encoding": string;
    "Direction": string;
    "Search": string;
}

/**
 * Frame is one captured data or status record.
 */
export interface Frame {
    "Seq": number;
    "Timestamp": time$0.Time;
    "Direction": string;
    "Port": string;
    "Length": number;
    "Data": string | null;
    "DisplayText": string;
    "DisplayHex": string;
    "DisplayDec": string;
    "DisplayOct": string;
    "DisplayBin": string;
    "Encoding": string;
    "Modbus": ModbusFrame | null;
}

/**
 * FramePage is a filtered frame page.
 */
export interface FramePage {
    "Frames": Frame[] | null;
    "Total": number;
    "NextOffset": number;
}

/**
 * ModbusFrame contains a best-effort Modbus RTU/ASCII parse.
 */
export interface ModbusFrame {
    "Protocol": string;
    "Slave": number;
    "Function": number;
    "FunctionHex": string;
    "PayloadHex": string;
    "CRCOK": boolean;
    "LRCOK": boolean;
    "Summary": string;
    "Error": string;
}

/**
 * QueryRequest asks for a filtered page of frames.
 */
export interface QueryRequest {
    "MonitorID": string;
    "Offset": number;
    "Limit": number;
    "Direction": string;
    "Search": string;
    "ModbusFunction": number;
}

/**
 * SessionInfo is a frontend-safe snapshot of a monitor session.
 */
export interface SessionInfo {
    "ID": string;
    "Name": string;
    "Provider": string;
    "PortA": string;
    "PortB": string;
    "Config": port$0.SerialConfig;
    "Encoding": string;
    "Status": string;
    "RxBytes": number;
    "TxBytes": number;
    "FrameCount": number;
    "StartedAt": time$0.Time;
    "StoppedAt": time$0.Time;
    "Error": string;
    "AutoSave": AutoSaveOptions;
}

/**
 * StartRequest starts a serial monitor session.
 */
export interface StartRequest {
    "ID": string;
    "Name": string;
    "Provider": string;
    "PortA": string;
    "PortB": string;
    "EndpointA": string;
    "EndpointB": string;
    "Config": port$0.SerialConfig;
    "Encoding": string;
    "AutoSave": AutoSaveOptions | null;
}
