// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Snapshot is an immutable view over a requested byte range.
 */
export interface Snapshot {
    /**
     * requested start offset
     */
    "Offset": number;

    /**
     * bytes in [Offset, Offset+len(Data))
     */
    "Data": string | null;

    /**
     * total bytes seen by the stream
     */
    "Total": number;

    /**
     * true if offset >= Total
     */
    "EOF": boolean;
}
