// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * BackendStatus is a frontend-safe snapshot of the active virtual serial
 * backend.
 */
export interface BackendStatus {
    "Name": string;
    "Available": boolean;
    "Message": string;
    "Reason": string;
    "RequiresAdmin": boolean;
}
