// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as port$0 from "../port/models.js";

/**
 * HandleStatus is a snapshot of a port handle's current state.
 * Immutable once created.
 */
export interface HandleStatus {
    "ID": string;
    "Config": port$0.SerialConfig;
    "IsOpen": boolean;
    "RxBytes": number;
    "TxBytes": number;
}

/**
 * OpenRequest bundles the parameters for opening a serial port.
 * Immutable once created.
 */
export interface OpenRequest {
    "Config": port$0.SerialConfig;
}
