// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as monitor$0 from "./monitor/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as port$0 from "./port/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../../time/models.js";

/**
 * AutoVirtualMonitorRequest starts monitoring one real serial port while
 * exposing an automatically-created virtual port for external tools.
 */
export interface AutoVirtualMonitorRequest {
    "ID": string;
    "Name": string;
    "Port": string;
    "Config": port$0.SerialConfig;
    "Encoding": string;
}

/**
 * BridgeInfo represents a serial bridge for the frontend.
 */
export interface BridgeInfo {
    "ID": string;
    "Port1": string;
    "Port2": string;
    "BaudRate": number;
}

/**
 * DecodeHexRequest bundles parameters for converting HEX to text.
 */
export interface DecodeHexRequest {
    "Content": string;
    "Encoding": string;
}

/**
 * EncodeTextRequest bundles parameters for converting text to HEX.
 */
export interface EncodeTextRequest {
    "Content": string;
    "Encoding": string;
}

/**
 * SendRequest bundles parameters for sending data.
 */
export interface SendRequest {
    "PortID": string;
    "Content": string;

    /**
     * "ascii" or "hex"
     */
    "Mode": string;
    "Encoding": string;
}

/**
 * SerialGraphBufferQuery reads one node's byte buffer.
 */
export interface SerialGraphBufferQuery {
    "GraphID": string;
    "NodeID": string;
    "Offset": number;
    "Length": number;
}

/**
 * SerialGraphEdgeSpec connects one output handle to one input handle.
 */
export interface SerialGraphEdgeSpec {
    "ID": string;
    "Source": string;
    "SourceHandle": string;
    "Target": string;
    "TargetHandle": string;
}

/**
 * SerialGraphFramePage is a filtered frame page for graph monitor nodes.
 */
export interface SerialGraphFramePage {
    "Frames": monitor$0.Frame[] | null;
    "Total": number;
    "NextOffset": number;
}

/**
 * SerialGraphFrameQuery reads one node's captured frame history.
 */
export interface SerialGraphFrameQuery {
    "GraphID": string;
    "NodeID": string;
    "Offset": number;
    "Limit": number;
    "Direction": string;
    "Search": string;
}

/**
 * SerialGraphNodeSpec is the backend representation of one graph node.
 */
export interface SerialGraphNodeSpec {
    "ID": string;
    "Type": string;
    "Config": { [_ in string]?: any } | null;
    "Position": SerialGraphPosition;
}

/**
 * SerialGraphNodeStatus is a frontend-safe snapshot of one runtime node.
 */
export interface SerialGraphNodeStatus {
    "ID": string;
    "Type": string;
    "Status": string;
    "RxBytes": number;
    "TxBytes": number;
    "FrameCount": number;
    "ResourceID": string;
    "Error": string;
}

/**
 * SerialGraphPosition is kept for frontend snapshot round-tripping.
 */
export interface SerialGraphPosition {
    "X": number;
    "Y": number;
}

/**
 * SerialGraphRuntimeInfo is a frontend-safe snapshot of one running graph.
 */
export interface SerialGraphRuntimeInfo {
    "ID": string;
    "Status": string;
    "StartedAt": time$0.Time;
    "StoppedAt": time$0.Time;
    "Error": string;
    "Nodes": SerialGraphNodeStatus[] | null;
}

/**
 * SerialGraphSendRequest injects bytes into a graph node.
 */
export interface SerialGraphSendRequest {
    "GraphID": string;
    "NodeID": string;
    "Content": string;
    "Mode": string;
    "Encoding": string;
}

/**
 * SerialGraphStartRequest starts one executable serial topology graph.
 */
export interface SerialGraphStartRequest {
    "ID": string;
    "Nodes": SerialGraphNodeSpec[] | null;
    "Edges": SerialGraphEdgeSpec[] | null;
}

/**
 * VirtualPairInfo represents a virtual serial pair for tests and bridge setup.
 */
export interface VirtualPairInfo {
    "ID": string;
    "Port1": string;
    "Port2": string;
}

/**
 * VirtualPortInfo represents a user-facing virtual serial port. The backing
 * peer is intentionally hidden from the frontend.
 */
export interface VirtualPortInfo {
    "ID": string;
    "Port": string;
}
