// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * PortInfo describes a discovered serial port with its hardware metadata.
 * Immutable once created.
 */
export interface PortInfo {
    /**
     * e.g. "/dev/tty.usbmodem...", "COM3"
     */
    "Name": string;

    /**
     * USB vendor name
     */
    "Vendor": string;

    /**
     * USB product name
     */
    "Product": string;

    /**
     * USB Vendor ID (hex, e.g. "2341")
     */
    "VID": string;

    /**
     * USB Product ID (hex, e.g. "0043")
     */
    "PID": string;

    /**
     * USB serial number
     */
    "SerialNumber": string;

    /**
     * true if port is USB-connected
     */
    "IsUSB": boolean;

    /**
     * human-readable name (may equal Name)
     */
    "FriendlyName": string;
}

/**
 * SerialConfig bundles the parameters for opening a serial port.
 * Immutable once created.
 */
export interface SerialConfig {
    "PortName": string;
    "BaudRate": number;

    /**
     * 5/6/7/8
     */
    "DataBits": number;

    /**
     * "1"|"1.5"|"2"
     */
    "StopBits": string;

    /**
     * "none"|"even"|"odd"|"mark"|"space"
     */
    "Parity": string;

    /**
     * "none"|"hw_rtscts"|"sw_xonxoff"
     */
    "FlowMode": string;

    /**
     * read buffer size in KB (default 32)
     */
    "ReadBufKB": number;
}
