// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * BridgeInfo represents a serial bridge for the frontend.
 */
export interface BridgeInfo {
    "ID": string;
    "Port1": string;
    "Port2": string;
    "BaudRate": number;
}

/**
 * SendRequest bundles parameters for sending data.
 */
export interface SendRequest {
    "PortID": string;
    "Content": string;

    /**
     * "ascii" or "hex"
     */
    "Mode": string;
}

/**
 * VirtualPairInfo represents a virtual serial pair for tests and bridge setup.
 */
export interface VirtualPairInfo {
    "ID": string;
    "Port1": string;
    "Port2": string;
}

/**
 * VirtualPortInfo represents a user-facing virtual serial port. The backing
 * peer is intentionally hidden from the frontend.
 */
export interface VirtualPortInfo {
    "ID": string;
    "Port": string;
}
