// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as port$0 from "./port/models.js";

/**
 * AutoVirtualMonitorRequest starts monitoring one real serial port while
 * exposing an automatically-created virtual port for external tools.
 */
export interface AutoVirtualMonitorRequest {
    "ID": string;
    "Name": string;
    "Port": string;
    "Config": port$0.SerialConfig;
    "Encoding": string;
}

/**
 * BridgeInfo represents a serial bridge for the frontend.
 */
export interface BridgeInfo {
    "ID": string;
    "Port1": string;
    "Port2": string;
    "BaudRate": number;
}

/**
 * DecodeHexRequest bundles parameters for converting HEX to text.
 */
export interface DecodeHexRequest {
    "Content": string;
    "Encoding": string;
}

/**
 * EncodeTextRequest bundles parameters for converting text to HEX.
 */
export interface EncodeTextRequest {
    "Content": string;
    "Encoding": string;
}

/**
 * SendRequest bundles parameters for sending data.
 */
export interface SendRequest {
    "PortID": string;
    "Content": string;

    /**
     * "ascii" or "hex"
     */
    "Mode": string;
    "Encoding": string;
}

/**
 * VirtualPairInfo represents a virtual serial pair for tests and bridge setup.
 */
export interface VirtualPairInfo {
    "ID": string;
    "Port1": string;
    "Port2": string;
}

/**
 * VirtualPortInfo represents a user-facing virtual serial port. The backing
 * peer is intentionally hidden from the frontend.
 */
export interface VirtualPortInfo {
    "ID": string;
    "Port": string;
}
