// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service is the serial module's facade exposed to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as buffer$0 from "./buffer/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as manager$0 from "./manager/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as port$0 from "./port/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CleanupVirtual stops all virtual pairs and bridges.
 */
export function CleanupVirtual(): $CancellablePromise<void> {
    return $Call.ByID(3380062301);
}

/**
 * ClosePort closes a serial port and removes its buffer.
 */
export function ClosePort(id: string): $CancellablePromise<void> {
    return $Call.ByID(358686901, id);
}

/**
 * CreateBridge creates a bridge between two serial ports.
 */
export function CreateBridge(id: string, port1: string, port2: string, baudRate: number): $CancellablePromise<$models.BridgeInfo | null> {
    return $Call.ByID(2000913547, id, port1, port2, baudRate);
}

/**
 * CreateVirtualPair creates a new virtual serial pair.
 */
export function CreateVirtualPair(id: string, port1Name: string, port2Name: string): $CancellablePromise<$models.VirtualPairInfo | null> {
    return $Call.ByID(3426122829, id, port1Name, port2Name);
}

/**
 * CreateVirtualPort creates a user-facing virtual serial port.
 */
export function CreateVirtualPort(id: string, portName: string): $CancellablePromise<$models.VirtualPortInfo | null> {
    return $Call.ByID(4156784338, id, portName);
}

/**
 * DecodeHexToText converts formatted HEX to text using the requested encoding.
 */
export function DecodeHexToText(req: $models.DecodeHexRequest): $CancellablePromise<string> {
    return $Call.ByID(4017514483, req);
}

/**
 * DeleteBridge removes a bridge.
 */
export function DeleteBridge(id: string): $CancellablePromise<void> {
    return $Call.ByID(2952555164, id);
}

/**
 * DeleteVirtualPair removes a virtual serial pair.
 */
export function DeleteVirtualPair(id: string): $CancellablePromise<void> {
    return $Call.ByID(1660406268, id);
}

/**
 * DeleteVirtualPort removes a user-facing virtual serial port.
 */
export function DeleteVirtualPort(id: string): $CancellablePromise<void> {
    return $Call.ByID(2248938995, id);
}

/**
 * EncodeTextToHex converts text to formatted HEX using the requested encoding.
 */
export function EncodeTextToHex(req: $models.EncodeTextRequest): $CancellablePromise<string> {
    return $Call.ByID(878865759, req);
}

/**
 * EnumeratePorts returns available serial ports.
 */
export function EnumeratePorts(): $CancellablePromise<port$0.PortInfo[] | null> {
    return $Call.ByID(2380440348);
}

/**
 * ListBridges returns all active bridges.
 */
export function ListBridges(): $CancellablePromise<$models.BridgeInfo[] | null> {
    return $Call.ByID(2577893816);
}

/**
 * ListPorts returns a snapshot of all open handles.
 */
export function ListPorts(): $CancellablePromise<manager$0.HandleStatus[] | null> {
    return $Call.ByID(2409741650);
}

/**
 * ListSystemFonts returns available font family candidates for terminal display.
 */
export function ListSystemFonts(): $CancellablePromise<string[] | null> {
    return $Call.ByID(887368283);
}

/**
 * ListVirtualPairs returns all virtual serial pairs.
 */
export function ListVirtualPairs(): $CancellablePromise<$models.VirtualPairInfo[] | null> {
    return $Call.ByID(3694945770);
}

/**
 * ListVirtualPorts returns all user-facing virtual serial ports.
 */
export function ListVirtualPorts(): $CancellablePromise<$models.VirtualPortInfo[] | null> {
    return $Call.ByID(1806471203);
}

/**
 * OpenPort opens a serial port and starts a read loop.
 */
export function OpenPort(req: manager$0.OpenRequest): $CancellablePromise<manager$0.HandleStatus | null> {
    return $Call.ByID(1403721065, req);
}

/**
 * Ping echoes msg back as "pong:<msg>", validating the binding channel.
 */
export function Ping(msg: string): $CancellablePromise<string> {
    return $Call.ByID(3334354438, msg);
}

/**
 * QueryPage returns a snapshot of the buffer for a given port handle.
 */
export function QueryPage(portID: string, offset: number, length: number): $CancellablePromise<buffer$0.Snapshot | null> {
    return $Call.ByID(257355161, portID, offset, length);
}

/**
 * ResetCounters clears RX and TX byte counters for an open port handle.
 */
export function ResetCounters(portID: string): $CancellablePromise<void> {
    return $Call.ByID(4017649972, portID);
}

/**
 * RestoreCounters sets RX and TX byte counters for an open port handle.
 */
export function RestoreCounters(portID: string, rxBytes: number, txBytes: number): $CancellablePromise<void> {
    return $Call.ByID(3925129033, portID, rxBytes, txBytes);
}

/**
 * Send sends data to the specified port.
 */
export function Send(req: $models.SendRequest): $CancellablePromise<number> {
    return $Call.ByID(304932660, req);
}
