// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service is the serial module's facade exposed to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as buffer$0 from "./buffer/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as fecbus$0 from "./fecbus/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as manager$0 from "./manager/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as modbus$0 from "./modbus/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as monitor$0 from "./monitor/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as port$0 from "./port/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddFecbusSlaveUnit adds or replaces one FECbus simulated slave address.
 */
export function AddFecbusSlaveUnit(sessionID: string, unit: fecbus$0.SlaveUnitState): $CancellablePromise<void> {
    return $Call.ByID(1156162034, sessionID, unit);
}

/**
 * AddModbusSlaveUnit adds or replaces one Unit ID in a slave simulation.
 */
export function AddModbusSlaveUnit(sessionID: string, unit: modbus$0.SlaveUnitSnapshot): $CancellablePromise<void> {
    return $Call.ByID(2829285044, sessionID, unit);
}

/**
 * CleanupVirtual stops all virtual pairs and bridges.
 */
export function CleanupVirtual(): $CancellablePromise<void> {
    return $Call.ByID(3380062301);
}

/**
 * ClearFecbusFrames clears FECbus frame history and counters.
 */
export function ClearFecbusFrames(id: string): $CancellablePromise<void> {
    return $Call.ByID(1260553897, id);
}

/**
 * ClearMonitorFrames clears captured monitor frames and counters.
 */
export function ClearMonitorFrames(id: string): $CancellablePromise<void> {
    return $Call.ByID(2442853029, id);
}

/**
 * CloseFecbusSession closes and removes a FECbus serial session.
 */
export function CloseFecbusSession(id: string): $CancellablePromise<void> {
    return $Call.ByID(1292629186, id);
}

/**
 * CloseModbusSession closes and removes a Modbus serial session.
 */
export function CloseModbusSession(id: string): $CancellablePromise<void> {
    return $Call.ByID(2804935884, id);
}

/**
 * ClosePort closes a serial port and removes its buffer.
 */
export function ClosePort(id: string): $CancellablePromise<void> {
    return $Call.ByID(358686901, id);
}

/**
 * CreateBridge creates a bridge between two serial ports.
 */
export function CreateBridge(id: string, port1: string, port2: string, baudRate: number): $CancellablePromise<$models.BridgeInfo | null> {
    return $Call.ByID(2000913547, id, port1, port2, baudRate);
}

/**
 * CreateVirtualPair creates a new virtual serial pair.
 */
export function CreateVirtualPair(id: string, port1Name: string, port2Name: string): $CancellablePromise<$models.VirtualPairInfo | null> {
    return $Call.ByID(3426122829, id, port1Name, port2Name);
}

/**
 * CreateVirtualPort creates a user-facing virtual serial port.
 */
export function CreateVirtualPort(id: string, portName: string): $CancellablePromise<$models.VirtualPortInfo | null> {
    return $Call.ByID(4156784338, id, portName);
}

/**
 * DecodeHexToText converts formatted HEX to text using the requested encoding.
 */
export function DecodeHexToText(req: $models.DecodeHexRequest): $CancellablePromise<string> {
    return $Call.ByID(4017514483, req);
}

/**
 * DeleteBridge removes a bridge.
 */
export function DeleteBridge(id: string): $CancellablePromise<void> {
    return $Call.ByID(2952555164, id);
}

/**
 * DeleteMonitor stops and removes a monitor session.
 */
export function DeleteMonitor(id: string): $CancellablePromise<void> {
    return $Call.ByID(2925886253, id);
}

/**
 * DeleteVirtualPair removes a virtual serial pair.
 */
export function DeleteVirtualPair(id: string): $CancellablePromise<void> {
    return $Call.ByID(1660406268, id);
}

/**
 * DeleteVirtualPort removes a user-facing virtual serial port.
 */
export function DeleteVirtualPort(id: string): $CancellablePromise<void> {
    return $Call.ByID(2248938995, id);
}

/**
 * EncodeTextToHex converts text to formatted HEX using the requested encoding.
 */
export function EncodeTextToHex(req: $models.EncodeTextRequest): $CancellablePromise<string> {
    return $Call.ByID(878865759, req);
}

/**
 * EnumeratePorts returns available serial ports.
 */
export function EnumeratePorts(): $CancellablePromise<port$0.PortInfo[] | null> {
    return $Call.ByID(2380440348);
}

/**
 * FecbusSendRequest sends one FECbus frame and optionally waits for an answer.
 */
export function FecbusSendRequest(req: fecbus$0.SendRequest): $CancellablePromise<fecbus$0.Transaction | null> {
    return $Call.ByID(3730420809, req);
}

/**
 * ListBridges returns all active bridges.
 */
export function ListBridges(): $CancellablePromise<$models.BridgeInfo[] | null> {
    return $Call.ByID(2577893816);
}

/**
 * ListFecbusSessions returns all open FECbus serial sessions.
 */
export function ListFecbusSessions(): $CancellablePromise<fecbus$0.SessionInfo[] | null> {
    return $Call.ByID(3393047171);
}

/**
 * ListFecbusSlaveUnits returns configured FECbus slave addresses.
 */
export function ListFecbusSlaveUnits(sessionID: string): $CancellablePromise<fecbus$0.SlaveUnitInfo[] | null> {
    return $Call.ByID(2350231212, sessionID);
}

/**
 * ListModbusSessions returns all open Modbus serial sessions.
 */
export function ListModbusSessions(): $CancellablePromise<modbus$0.SessionInfo[] | null> {
    return $Call.ByID(2367745677);
}

/**
 * ListModbusSlaveUnits returns configured Unit IDs for a Modbus session.
 */
export function ListModbusSlaveUnits(sessionID: string): $CancellablePromise<modbus$0.SlaveUnitInfo[] | null> {
    return $Call.ByID(1676937614, sessionID);
}

/**
 * ListMonitors returns all serial monitor sessions.
 */
export function ListMonitors(): $CancellablePromise<monitor$0.SessionInfo[] | null> {
    return $Call.ByID(3764334461);
}

/**
 * ListPorts returns a snapshot of all open handles.
 */
export function ListPorts(): $CancellablePromise<manager$0.HandleStatus[] | null> {
    return $Call.ByID(2409741650);
}

/**
 * ListSystemFonts returns available font family candidates for terminal display.
 */
export function ListSystemFonts(): $CancellablePromise<string[] | null> {
    return $Call.ByID(887368283);
}

/**
 * ListVirtualPairs returns all virtual serial pairs.
 */
export function ListVirtualPairs(): $CancellablePromise<$models.VirtualPairInfo[] | null> {
    return $Call.ByID(3694945770);
}

/**
 * ListVirtualPorts returns all user-facing virtual serial ports.
 */
export function ListVirtualPorts(): $CancellablePromise<$models.VirtualPortInfo[] | null> {
    return $Call.ByID(1806471203);
}

/**
 * ModbusMasterRequest runs one Modbus master transaction.
 */
export function ModbusMasterRequest(req: modbus$0.MasterRequest): $CancellablePromise<modbus$0.Transaction | null> {
    return $Call.ByID(3881180191, req);
}

/**
 * ModbusReadRegisters reads and decodes one Modbus register block.
 */
export function ModbusReadRegisters(req: modbus$0.RegisterReadRequest): $CancellablePromise<modbus$0.RegisterReadResult | null> {
    return $Call.ByID(2930160550, req);
}

/**
 * ModbusScanRegisters scans a Modbus register range.
 */
export function ModbusScanRegisters(req: modbus$0.RegisterScanRequest): $CancellablePromise<modbus$0.RegisterScanResult | null> {
    return $Call.ByID(1992987289, req);
}

/**
 * ModbusScanUnitIDs probes a set of Modbus Unit IDs.
 */
export function ModbusScanUnitIDs(req: modbus$0.UnitScanRequest): $CancellablePromise<modbus$0.UnitScanResult | null> {
    return $Call.ByID(2190012875, req);
}

/**
 * OpenFecbusSession opens a dedicated FECbus serial session.
 */
export function OpenFecbusSession(req: fecbus$0.OpenSessionRequest): $CancellablePromise<fecbus$0.SessionInfo | null> {
    return $Call.ByID(3696073086, req);
}

/**
 * OpenModbusSession opens a dedicated Modbus serial session.
 */
export function OpenModbusSession(req: modbus$0.OpenSessionRequest): $CancellablePromise<modbus$0.SessionInfo | null> {
    return $Call.ByID(95138080, req);
}

/**
 * OpenPort opens a serial port and starts a read loop.
 */
export function OpenPort(req: manager$0.OpenRequest): $CancellablePromise<manager$0.HandleStatus | null> {
    return $Call.ByID(1403721065, req);
}

/**
 * Ping echoes msg back as "pong:<msg>", validating the binding channel.
 */
export function Ping(msg: string): $CancellablePromise<string> {
    return $Call.ByID(3334354438, msg);
}

/**
 * QueryFecbusFrames returns a filtered FECbus frame history page.
 */
export function QueryFecbusFrames(req: fecbus$0.QueryRequest): $CancellablePromise<fecbus$0.FramePage | null> {
    return $Call.ByID(3006540140, req);
}

/**
 * QueryMonitorFrames returns a filtered page of monitor frames.
 */
export function QueryMonitorFrames(req: monitor$0.QueryRequest): $CancellablePromise<monitor$0.FramePage | null> {
    return $Call.ByID(1659843558, req);
}

/**
 * QueryPage returns a snapshot of the buffer for a given port handle.
 */
export function QueryPage(portID: string, offset: number, length: number): $CancellablePromise<buffer$0.Snapshot | null> {
    return $Call.ByID(257355161, portID, offset, length);
}

/**
 * RemoveFecbusSlaveUnit removes one FECbus simulated slave address.
 */
export function RemoveFecbusSlaveUnit(sessionID: string, address: number): $CancellablePromise<void> {
    return $Call.ByID(3188425671, sessionID, address);
}

/**
 * RemoveModbusSlaveUnit removes one Unit ID from a slave simulation.
 */
export function RemoveModbusSlaveUnit(sessionID: string, unitID: number): $CancellablePromise<void> {
    return $Call.ByID(648861305, sessionID, unitID);
}

/**
 * ResetCounters clears RX and TX byte counters for an open port handle.
 */
export function ResetCounters(portID: string): $CancellablePromise<void> {
    return $Call.ByID(4017649972, portID);
}

/**
 * RestoreCounters sets RX and TX byte counters for an open port handle.
 */
export function RestoreCounters(portID: string, rxBytes: number, txBytes: number): $CancellablePromise<void> {
    return $Call.ByID(3925129033, portID, rxBytes, txBytes);
}

/**
 * Send sends data to the specified port.
 */
export function Send(req: $models.SendRequest): $CancellablePromise<number> {
    return $Call.ByID(304932660, req);
}

/**
 * StartAutoVirtualMonitor starts monitoring a real port and creates one
 * user-facing virtual port that external serial tools can connect to.
 */
export function StartAutoVirtualMonitor(req: $models.AutoVirtualMonitorRequest): $CancellablePromise<monitor$0.SessionInfo | null> {
    return $Call.ByID(999938326, req);
}

/**
 * StartFecbusSlave starts FECbus device simulation for an open session.
 */
export function StartFecbusSlave(req: fecbus$0.StartSlaveRequest): $CancellablePromise<fecbus$0.SessionInfo | null> {
    return $Call.ByID(4144070753, req);
}

/**
 * StartModbusSlave starts slave simulation for an open Modbus session.
 */
export function StartModbusSlave(req: modbus$0.StartSlaveRequest): $CancellablePromise<modbus$0.SessionInfo | null> {
    return $Call.ByID(551114279, req);
}

/**
 * StartMonitor starts a bridge-based serial monitor session.
 */
export function StartMonitor(req: monitor$0.StartRequest): $CancellablePromise<monitor$0.SessionInfo | null> {
    return $Call.ByID(3071407328, req);
}

/**
 * StopFecbusSlave stops FECbus device simulation for an open session.
 */
export function StopFecbusSlave(id: string): $CancellablePromise<void> {
    return $Call.ByID(915799721, id);
}

/**
 * StopModbusSlave stops slave simulation for an open Modbus session.
 */
export function StopModbusSlave(id: string): $CancellablePromise<void> {
    return $Call.ByID(755939087, id);
}

/**
 * StopMonitor stops a monitor session while keeping captured frames available.
 */
export function StopMonitor(id: string): $CancellablePromise<void> {
    return $Call.ByID(2368061992, id);
}

/**
 * UpdateFecbusSlaveState replaces FECbus device simulation state.
 */
export function UpdateFecbusSlaveState(sessionID: string, state: fecbus$0.SlaveState): $CancellablePromise<void> {
    return $Call.ByID(367919167, sessionID, state);
}

/**
 * UpdateModbusSlaveData replaces the slave simulation data model.
 */
export function UpdateModbusSlaveData(sessionID: string, data: modbus$0.DataModelSnapshot): $CancellablePromise<void> {
    return $Call.ByID(184207884, sessionID, data);
}

/**
 * UpdateModbusSlaveUnitData replaces one Unit ID data model.
 */
export function UpdateModbusSlaveUnitData(sessionID: string, unitID: number, data: modbus$0.DataModelSnapshot): $CancellablePromise<void> {
    return $Call.ByID(1856574682, sessionID, unitID, data);
}
