// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Snapshot is an immutable view over a requested byte range.
 */
export interface Snapshot {
    /**
     * requested start offset
     */
    "Offset": number;

    /**
     * bytes in [Offset, Offset+len(Data))
     */
    "Data": string | null;

    /**
     * chunk metadata overlapping the returned Data range
     */
    "Chunks": SnapshotChunk[] | null;

    /**
     * total bytes seen by the stream
     */
    "Total": number;

    /**
     * true if offset >= Total
     */
    "EOF": boolean;
}

/**
 * SnapshotChunk is one retained received block that overlaps a Snapshot range.
 */
export interface SnapshotChunk {
    /**
     * byte offset from the start of the stream
     */
    "Offset": number;

    /**
     * capture time for this block, empty when unknown
     */
    "Timestamp": string;

    /**
     * bytes in this block slice (copy, safe to hold)
     */
    "Data": string | null;
}
