// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as port$0 from "../port/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../../../time/models.js";

/**
 * AnnotatedFrame is a frontend-safe semantic view of one captured FECbus frame.
 */
export interface AnnotatedFrame {
    "Segments": FrameSegment[] | null;
    "DataFields": FieldAnnotation[] | null;
    "Function": FunctionInfo;
    "GroupKey": string;
    "GroupColorIndex": number;
    "Summary": string;
    "Warnings": string[] | null;
}

/**
 * CustomDataFieldDefinition is a user-defined data segment field.
 */
export interface CustomDataFieldDefinition {
    "Key": string;
    "Label": string;
    "Offset": number;
    "Length": number;
    "Type": string;
    "Endian": string;
    "Enum": { [_ in `${number}`]?: string } | null;
    "Meaning": string;
}

/**
 * CustomFunctionDefinition customizes Appendix C function names and payload fields.
 */
export interface CustomFunctionDefinition {
    "Code": FunctionCode;
    "Name": string;
    "Description": string;
    "Direction": string;
    "Answer": boolean;
    "Fields": CustomDataFieldDefinition[] | null;
}

/**
 * FieldAnnotation annotates one application data field.
 */
export interface FieldAnnotation {
    "Key": string;
    "Label": string;
    "Start": number;
    "End": number;
    "Hex": string;
    "Value": any;
    "ValueText": string;
    "Meaning": string;
}

/**
 * Frame is one decoded FECbus serial frame.
 */
export interface Frame {
    "Type": FrameType;
    "TargetAddress": number;
    "Priority": number;
    "SourceAddress": number;
    "MessageNumber": number;
    "GroupNumber": number;
    "Data": string | null;
    "Raw": string | null;
    "CRCOK": boolean;
    "Timestamp": time$0.Time;
}

/**
 * FramePage is a page of captured FECbus frames.
 */
export interface FramePage {
    "Frames": FrameRecord[] | null;
    "Offset": number;
    "Limit": number;
    "Total": number;
    "EOF": boolean;
}

/**
 * FrameRecord stores one captured FECbus TX/RX frame.
 */
export interface FrameRecord {
    "Seq": number;
    "SessionID": string;
    "Direction": string;
    "Frame": Frame;
    "Hex": string;
    "Error": string;
    "Timestamp": time$0.Time;
    "Annotated": AnnotatedFrame;
}

/**
 * FrameSegment annotates one raw byte range in an encoded serial frame.
 */
export interface FrameSegment {
    "Key": string;
    "Label": string;
    "Start": number;
    "End": number;
    "Hex": string;
    "Value": any;
    "ValueText": string;
    "Meaning": string;
}

/**
 * FrameType is the FECbus FT field.
 */
export enum FrameType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    FrameTypeRequest = 0,
    FrameTypeAnswer = 1,
};

/**
 * FunctionCode is the first byte of the FECbus message data.
 */
export enum FunctionCode {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    FunctionSyncHeartbeat = 0,
    FunctionReset = 1,
    FunctionSilence = 2,
    FunctionSelfTest = 3,
    FunctionBroadcastClock = 4,
    FunctionNotifyUrgentEvent = 5,
    FunctionNotifyGeneralEvent = 6,
    FunctionNotifyDebugEvent = 7,
    FunctionStatusAnswer = 15,
    FunctionDeviceUrgentEvent = 17,
    FunctionDeviceGeneralEvent = 18,
    FunctionDeviceDebugEvent = 19,
    FunctionHeartbeatPollInfo = 20,
    FunctionPollConnectionStatus = 33,
    FunctionQueryDeviceStatus = 34,
    FunctionQueryConfig = 35,
    FunctionQueryIdentifier = 36,
    FunctionQueryParameter = 37,
    FunctionQueryComment = 38,
    FunctionQueryProgramming = 39,
    FunctionQueryRegistration = 40,
    FunctionQueryCurrentEvent = 41,
    FunctionQueryHistoryEvent = 42,
    FunctionStopEventQuery = 43,
    FunctionQueryProtocolVersion = 44,
    FunctionQueryDeviceList = 45,
};

/**
 * FunctionInfo describes one function code from GB 4717-2024 Appendix C table C.2.
 */
export interface FunctionInfo {
    "Code": FunctionCode;
    "Hex": string;
    "Name": string;
    "Description": string;
    "Direction": string;
    "Answer": boolean;
    "Custom": boolean;
    "Reserved": boolean;
}

/**
 * OpenSessionRequest opens a dedicated FECbus serial session.
 */
export interface OpenSessionRequest {
    "ID": string;
    "Name": string;
    "Role": SessionRole;
    "Config": port$0.SerialConfig;
    "Endpoint": string;
    "TimeoutMs": number;
    "Retries": number;
}

/**
 * QueryRequest filters frame history.
 */
export interface QueryRequest {
    "SessionID": string;
    "Offset": number;
    "Limit": number;
    "Direction": string;
    "Search": string;
    "Custom": CustomFunctionDefinition[] | null;
}

/**
 * SendRequest describes one FECbus master/device transmission.
 */
export interface SendRequest {
    "SessionID": string;
    "FrameType": FrameType;
    "TargetAddress": number;
    "Priority": number;
    "SourceAddress": number;
    "MessageNumber": number;
    "GroupNumber": number;
    "Function": FunctionCode;
    "DataHex": string;
    "Data": string | null;
    "ExpectAnswer": boolean;
    "TimeoutMs": number;
    "Retries": number;
}

/**
 * SessionInfo is a frontend-safe snapshot of a FECbus session.
 */
export interface SessionInfo {
    "ID": string;
    "Name": string;
    "Role": SessionRole;
    "Config": port$0.SerialConfig;
    "Status": string;
    "RxBytes": number;
    "TxBytes": number;
    "SlaveRunning": boolean;
    "SourceAddress": number;
    "TargetAddress": number;
    "SlaveUnits": SlaveUnitInfo[] | null;
    "StartedAt": time$0.Time;
    "StoppedAt": time$0.Time;
    "LastError": string;
}

/**
 * SessionRole fixes whether a FECbus session acts as a controller or device.
 */
export enum SessionRole {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    SessionRoleMaster = "master",
    SessionRoleSlave = "slave",
};

/**
 * SlaveState configures automatic status responses for device simulation.
 */
export interface SlaveState {
    "Address": number;
    "DefaultStatus": StatusCode;
    "AutoStatusAnswer": boolean;
    "AcceptBroadcast": boolean;
    "AnswerPayloadByFunction": { [_ in FunctionCode]?: string | null } | null;
}

/**
 * SlaveUnitInfo is a frontend-safe summary for one simulated slave address.
 */
export interface SlaveUnitInfo {
    "Address": number;
    "DefaultStatus": StatusCode;
    "AutoStatusAnswer": boolean;
    "AcceptBroadcast": boolean;
}

/**
 * SlaveUnitState configures one simulated FECbus slave address.
 */
export interface SlaveUnitState {
    "Address": number;
    "DefaultStatus": StatusCode;
    "AutoStatusAnswer": boolean;
    "AcceptBroadcast": boolean;
    "AnswerPayloadByFunction": { [_ in FunctionCode]?: string | null } | null;
}

/**
 * StartSlaveRequest starts FECbus slave simulation for one session.
 */
export interface StartSlaveRequest {
    "SessionID": string;
    "State": SlaveState;
    "Units": SlaveUnitState[] | null;
}

/**
 * StatusCode is the second byte of a status-answer frame.
 */
export enum StatusCode {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    StatusGroupEnd = 0,
    StatusCRCError = 1,
    StatusInvalidService = 2,
    StatusUnitFault = 3,
    StatusBusy = 4,
    StatusUnrecognizedCommand = 5,
    StatusAddressNotFound = 6,
    StatusParameterError = 7,
    StatusProcessing = 8,
    StatusEventEnd = 9,
    StatusReceivedOK = 10,
};

/**
 * Transaction captures one FECbus request/answer exchange.
 */
export interface Transaction {
    "ID": string;
    "SessionID": string;
    "StartedAt": time$0.Time;
    "CompletedAt": time$0.Time;
    "Request": Frame;
    "Response": Frame | null;
    "RequestFrameHex": string;
    "ResponseFrameHex": string;
    "BytesWritten": number;
    "Error": string;
}
