// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FileResult is a workspace JSON file read result.
 */
export interface FileResult {
    "Path": string;
    "Content": string;
}

/**
 * LastWorkspaceResult is returned during startup auto-load.
 */
export interface LastWorkspaceResult {
    "Found": boolean;
    "Path": string;
    "Content": string;
}
