// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service exposes workspace JSON file persistence to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * DefaultWorkspacePath returns the built-in workspace save location.
 */
export function DefaultWorkspacePath(): $CancellablePromise<string> {
    return $Call.ByID(4099723456);
}

/**
 * ExportWorkspace writes content to path without changing the last workspace.
 */
export function ExportWorkspace(path: string, content: string): $CancellablePromise<void> {
    return $Call.ByID(3559906368, path, content);
}

/**
 * LoadLastWorkspace loads the remembered workspace file. Missing files are not
 * fatal: the app should start clean if the previous file is unavailable.
 */
export function LoadLastWorkspace(): $CancellablePromise<$models.LastWorkspaceResult | null> {
    return $Call.ByID(2130345542);
}

/**
 * ReadWorkspace reads a workspace JSON file from path.
 */
export function ReadWorkspace(path: string): $CancellablePromise<$models.FileResult | null> {
    return $Call.ByID(900512094, path);
}

/**
 * RememberLastWorkspace stores the last workspace file path for startup load.
 */
export function RememberLastWorkspace(path: string): $CancellablePromise<void> {
    return $Call.ByID(75507439, path);
}

/**
 * SaveWorkspace writes content to path and remembers it as the last workspace.
 */
export function SaveWorkspace(path: string, content: string): $CancellablePromise<void> {
    return $Call.ByID(410233597, path, content);
}

/**
 * SelectWorkspaceOpenPath prompts for a workspace JSON file to open.
 */
export function SelectWorkspaceOpenPath(currentPath: string): $CancellablePromise<string> {
    return $Call.ByID(2025476813, currentPath);
}

/**
 * SelectWorkspaceSavePath prompts for a workspace JSON file save target.
 */
export function SelectWorkspaceSavePath(currentPath: string): $CancellablePromise<string> {
    return $Call.ByID(2614332356, currentPath);
}
